### ISSUE TITLE
extends Array support is breaking ts-node

### ISSUE THREAD

**Issue by binarykitchen** [tsconfig/bases#167]
ts-node is throwing this error when you use the new feature, have an array under `extends` and run Jest tests whose config files are in TS:

```
  TypeError: value.replace is not a function
      at normalizeSlashes (/home/michael-heuberger/code/artemis/node_modules/ts-node/dist/util.js:63:18)
      at Object.getExtendsConfigPath (/home/michael-heuberger/code/artemis/node_modules/ts-node/dist/ts-internals.js:24:54)
      at readConfig (/home/michael-heuberger/code/artemis/node_modules/ts-node/dist/configuration.js:127:64)
      at findAndReadConfig (/home/michael-heuberger/code/artemis/node_modules/ts-node/dist/configuration.js:50:84)
      at create (/home/michael-heuberger/code/artemis/node_modules/ts-node/dist/index.js:146:69)
      at Module.register (/home/michael-heuberger/code/artemis/node_modules/ts-node/dist/index.js:127:19)
      at registerTsNode (/home/michael-heuberger/code/artemis/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:175:19)
      at async loadTSConfigFile (/home/michael-heuberger/code/artemis/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:151:30)
      at async readConfigFileAndSetRootDir (/home/michael-heuberger/code/artemis/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:104:22)
      at async readInitialOptions (/home/michael-heuberger/code/artemis/node_modules/jest-config/build/index.js:389:15)

```

when having

```
"extends": ["@artemis/tsconfig-node/tsconfig", "@tsconfig/create-react-app/tsconfig"],
```

**Comment by orta** [comment]
Perhaps you need to update ts-node? Or send them a PR helping their support for array extends 👍🏻

**Comment by binarykitchen** [comment]
Already using latest version here and sorry, as a father I do not have time.

**Comment by JamieMagee** [comment]
This is already fixed in `ts-node`, but not yet in a release. See https://github.com/TypeStrong/ts-node/pull/1958

**Comment by jensbodal** [comment]
There does not seem to be any immediate plan to release a version with support for Typescript v5. This is likely the early days of many similar issues across different repos (like this one and commitlint) as people begin to upgrade to v5. 

[ts-node recommends](https://github.com/TypeStrong/ts-node/discussions/1977) installing from git to get latest changes which is not a great solution for us.

[ts-node milestones](https://github.com/TypeStrong/ts-node/milestones)

**Comment by schamane** [comment]
Not only ts-node, also tsconfig-resolver is not parsing array on extension attribute :(
This breaks eslint and bunch of other frameworks...

<img width="892" alt="image" src="https://github.com/tsconfig/bases/assets/132251/5f1e8584-43ec-4f36-b181-68d704622592">

**Comment by FreePhoenix888** [comment]
https://github.com/TypeStrong/ts-node/issues/2000
