### ISSUE TITLE
[Svelte] `Unknown compiler option 'verbatimModuleSyntax'` after updating from `@tsconfig/svelte: 3.0.0` to `@tsconfig/svelte: ^4.0.1`

### ISSUE THREAD

**Issue by Snailedlt** [tsconfig/bases#190]
## Exception

I get the following error after updating from version 3.0.0 to 4.0.1 via dependabot:
```sh
(!) Plugin typescript: @rollup/plugin-typescript TS5023: Unknown compiler option 'verbatimModuleSyntax'.
node_modules/@tsconfig/svelte/tsconfig.json: (13:5)
[!] (plugin typescript) Error: @rollup/plugin-typescript: Couldn't process compiler options
Error: @rollup/plugin-typescript: Couldn't process compiler options
    at error (D:\code\egde\STAF\Selvbetjening-frontend\node_modules\rollup\dist\shared\rollup.js:198:30)
    at throwPluginError (D:\code\egde\STAF\Selvbetjening-frontend\node_modules\rollup\dist\shared\rollup.js:21718:12)
    at Object.error (D:\code\egde\STAF\Selvbetjening-frontend\node_modules\rollup\dist\shared\rollup.js:22672:20)
    at emitParsedOptionsErrors (D:\code\egde\STAF\Selvbetjening-frontend\node_modules\@rollup\plugin-typescript\dist\cjs\index.js:369:17)
    at Object.buildStart (D:\code\egde\STAF\Selvbetjening-frontend\node_modules\@rollup\plugin-typescript\dist\cjs\index.js:767:13)
    at D:\code\egde\STAF\Selvbetjening-frontend\node_modules\rollup\dist\shared\rollup.js:22879:40
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at PluginDriver.hookParallel (D:\code\egde\STAF\Selvbetjening-frontend\node_modules\rollup\dist\shared\rollup.js:22807:9)
    at D:\code\egde\STAF\Selvbetjening-frontend\node_modules\rollup\dist\shared\rollup.js:23767:13
```

## Fix

The issues is fixed when I remove `"verbatimModuleSyntax": true,` from the base tsconfig.json that is bundled with the node module at `@tsconfig/svelte/tsconfig.json`.

## Config & Versions

Here is my `tsconfig.json`
```json
{
  "extends": "@tsconfig/svelte/tsconfig.json",
  "compilerOptions": {
    "allowJs": true
  },
  "exclude": [
    ".github/workflows",
    ".idea",
    ".vscode",
    "node_modules",
    ".env",
    ".gitignore",
    ".prettierignore",
    ".prettierrc",
    "bable.config.js",
    "jest.config.js",
    "package-lock.json",
    "package.json",
    "rollup.config.js",
    "svelte.config.js"
  ]
}
```

Versions:
```
Node: v18.6.0
npm: 8.13.2
"@tsconfig/svelte": "^4.0.1",
"@rollup/plugin-typescript": "^11.1.0"
"rollup": "^2.79.1"
"typescript": "^4.9.5"
"svelte": "^3.59.1",
```

**Comment by orta** [comment]
https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax was introduced in TypeScript 5.0

**Comment by Snailedlt** [comment]
@orta Thank you for the quick response

I couldn't find any comment on why the new version was a major version, nor does it have a Typescript 5.0 dependency.
Perhaps it should have been mentioned in the README, and/or added as a dependency so dependabot can handle the update correctly?

**Comment by Snailedlt** [comment]
A changelog would be very useful!
