### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by ageha734** [tsconfig/bases#201]
### Error1
```json
{
  "extends": "@tsconfig/next/tsconfig.json",
  "compilerOptions": {
    "paths": {
      "lib/*": [
        "lib/*"
      ]
    }
  }
}
```

`TypeError: Cannot read properties of undefined (reading 'push')
    at writeConfigurationDefaults (/node_modules/next/dist/lib/typescript/writeConfigurationDefaults.js:227:30)
    at async verifyTypeScriptSetup (/node_modules/next/dist/lib/verifyTypeScriptSetup.js:120:9)
    at async DevServer.verifyTypeScript (/node_modules/next/dist/server/dev/next-dev-server.js:648:34)
    at async DevServer.prepareImpl (/node_modules/next/dist/server/dev/next-dev-server.js:672:9)
    at async NextServer.prepare /node_modules/next/dist/server/next.js:165:13)
    at async Server.<anonymous> (/next/dist/server/lib/render-server.js:123:17) {
  type: 'TypeError'
}`

### Error2
```json
{
  "extends": "node_modules/@tsconfig/next/tsconfig.json",
  "compilerOptions": {
    "paths": {
      "lib/*": [
        "lib/*"
      ]
    }
  }
}
```

`error TS6053: File 'node_modules/@tsconfig/next/tsconfig.json' not found.`

### Development environment

- os: macOS13.4.1
- node: 18.16.0
- pnpm 8.5.1
- next: 13.4.5
- preact: 10.15.1
- react: 18.2.0
- react-dom: 18.2.0
- @tsconfig/next: 2.0.0

### List of commands executed

- `pnpm dev`
- `pnpm remove @tsconfig/next`
- `pnpm add -D @tsconfig/next`
- `pnpm dev`

### summary
I can't build with an error even after changing the path to the Extended Settings file and re-installing.

**Comment by orta** [comment]
Did you install the packages?

**Comment by ageha734** [comment]
Yes. Installed and used.

**Comment by ageha734** [comment]
I think the proper setting is 
```json
"extends":"@tsconfig/next/tsconfig.json"
```
but is there any other place to set it?

**Comment by orta** [comment]
Nope that goes in your tsconfig

**Comment by emkman** [comment]
@ageha734 the issue is with Next.js. It expects an `includes` key in your tsconfig.json. Instead of
```
{
  "extends": "@tsconfig/next/tsconfig.json"
}
```
you need something like this
```
{
  "extends": "@tsconfig/next/tsconfig.json",
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

Generally, it seems like this package doesn't play that well with Next.js expectations which does a lot of automatic injection into your tsconfig.json and so it's probably better to just copy and paste from https://github.com/tsconfig/bases/blob/main/bases/next.json manually.
